#!name=NGA图片域名修复
#!desc=img(\d*).nga.178.com -> img$1.nga.cn（QX 302版，模块方式）
#!author=Ka1er

[rewrite]
^https?://img(\d*)\.nga\.178\.com\/(.*) url 302 https://img$1.nga.cn/$2

[mitm]
hostname = %APPEND% img.nga.178.com, img0.nga.178.com, img1.nga.178.com, img2.nga.178.com, img3.nga.178.com, img4.nga.178.com, img5.nga.178.com, img6.nga.178.com, img7.nga.178.com, img8.nga.178.com, img9.nga.178.com, img10.nga.178.com
