#!name=NGA图片域名修复
#!desc=img(\d*).nga.178.com -> img$1.nga.cn（QX 302版，模块方式）
#!author=Ka1er

[rewrite]
^https?://img(\d*)\.nga\.178\.com\/(.*) url 302 https://img$1.nga.cn/$2

[mitm]
hostname = %APPEND% \*.nga.178.com
